"""Single wiring point of the ``FinancialComputations`` port.

:class:`DomainComputations` implements the port with the domain functions of
cycle 001 (``dominio/metricas.py``, which in turn uses ``dominio/simulacao.py``)
over the injected repository, in every mode: with fixtures the repository is
:class:`~bussola_mcp.ferramentas.fixture_backends.FixtureRepository`, in
production ``RepositorioBigQuery``. The fixtures v1 are generated by the same
code, so fake mode and production answer with the same rules.

Failure mapping (the tool runner turns both into the error envelope):

- ``MetricError`` (``ENTRADA_INVALIDA``, ``DADOS_INSUFICIENTES``,
  ``PRAZO_IMPLAUSIVEL``) → :class:`DomainError` with the same code and message;
- ``RepositoryUnavailableError`` → :class:`BackendUnavailable`
  (``INDISPONIVEL``), with no detail for the client.
"""

from collections.abc import Callable
from pathlib import Path

from bussola_mcp.dominio import metricas
from bussola_mcp.dominio.interfaces import RepositorioFinanceiro
from bussola_mcp.dominio.metricas import MetricError, MetricResult
from bussola_mcp.dominio.repositorio_bq import RepositoryUnavailableError
from bussola_mcp.ferramentas.ports import (
    BackendUnavailable,
    Computation,
    DomainError,
    FinancialComputations,
)


def _to_computation(call: Callable[[], MetricResult]) -> Computation:
    try:
        result = call()
    except MetricError as exc:
        raise DomainError(exc.codigo, exc.mensagem) from exc
    except RepositoryUnavailableError as exc:
        raise BackendUnavailable() from exc
    return Computation(dados=result.dados, periodo=result.periodo, avisos=tuple(result.avisos))


class DomainComputations:
    """Implements ``FinancialComputations`` with ``metricas.<tool>`` over a repository."""

    def __init__(self, repository: RepositorioFinanceiro) -> None:
        self.repository = repository

    def perfil_financeiro(self, id_usuario: str, ate_anomes: int) -> Computation:
        return _to_computation(
            lambda: metricas.perfil_financeiro(self.repository, id_usuario, ate_anomes)
        )

    def capacidade_poupanca(self, id_usuario: str, ate_anomes: int) -> Computation:
        return _to_computation(
            lambda: metricas.capacidade_poupanca(self.repository, id_usuario, ate_anomes)
        )

    def oportunidades_corte(self, id_usuario: str, ate_anomes: int, top_n: int) -> Computation:
        return _to_computation(
            lambda: metricas.oportunidades_corte(self.repository, id_usuario, ate_anomes, top_n)
        )

    def dividas_e_parcelas(self, id_usuario: str, ate_anomes: int) -> Computation:
        return _to_computation(
            lambda: metricas.dividas_e_parcelas(self.repository, id_usuario, ate_anomes)
        )

    def simular_objetivo(
        self,
        id_usuario: str,
        ate_anomes: int,
        valor_alvo: float,
        prazo_meses: int | None,
        aporte_mensal: float | None,
        usar_saldo_atual: bool,
    ) -> Computation:
        return _to_computation(
            lambda: metricas.simular_objetivo(
                self.repository,
                id_usuario,
                ate_anomes,
                valor_alvo,
                prazo_meses=prazo_meses,
                aporte_mensal=aporte_mensal,
                usar_saldo_atual=usar_saldo_atual,
            )
        )

    def comparar_cenarios(
        self, id_usuario: str, ate_anomes: int, valor_alvo: float, prazo_meses: int
    ) -> Computation:
        return _to_computation(
            lambda: metricas.comparar_cenarios(
                self.repository, id_usuario, ate_anomes, valor_alvo, prazo_meses
            )
        )

    def resumo_mes(self, id_usuario: str, ate_anomes: int, anomes: int) -> Computation:
        return _to_computation(
            lambda: metricas.resumo_mes(self.repository, id_usuario, ate_anomes, anomes)
        )

    def referencia_coorte(self, id_usuario: str, ate_anomes: int, categoria: str) -> Computation:
        return _to_computation(
            lambda: metricas.referencia_coorte(self.repository, id_usuario, ate_anomes, categoria)
        )


def build_computations(
    repository: RepositorioFinanceiro, fixtures_dir: Path | str | None = None
) -> FinancialComputations:
    """Adapter of the computation port used by the server, in every mode.

    ``fixtures_dir`` is kept for compatibility: the repository already points
    at the fixtures when they are in use.
    """
    del fixtures_dir
    return DomainComputations(repository)
